spring:
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 746155544462-5t6vmkefn0pbgma7fcp8ua0211q49dbu.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email


#
#cors:
#  allowed-origins: 'http://localhost:3000'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600
#
## jwt secret key 설정
#jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'
#
## 토큰 관련 secret Key 및 RedirectUri 설정
#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpiry: 1800000
#    refreshTokenExpiry: 604800000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth/redirect